import type { ApiClientFacade } from '../api-client.ts';
import { headersMethod } from './headers.ts';
import { urlMethod } from './url.ts';
import { requestMethod } from './request.ts';
import { accountIdentityMethod } from './account-identity.ts';
import { authProvidersMethod } from './auth-providers.ts';
import { requestPasswordResetMethod } from './request-password-reset.ts';
import { completePasswordResetMethod } from './complete-password-reset.ts';
import { confirmEmailMethod } from './confirm-email.ts';
import { approveDeviceMethod } from './approve-device.ts';
import { claimUsernameMethod } from './claim-username.ts';
import { updateAccountProfileMethod } from './update-account-profile.ts';
import { addAccountEmailMethod } from './add-account-email.ts';
import { resendAccountEmailMethod } from './resend-account-email.ts';
import { setPrimaryAccountEmailMethod } from './set-primary-account-email.ts';
import { deleteAccountEmailMethod } from './delete-account-email.ts';
import { updateAccountPasswordMethod } from './update-account-password.ts';
import { unlinkAccountProviderMethod } from './unlink-account-provider.ts';
import { accountSessionsMethod } from './account-sessions.ts';
import { revokeAccountSessionMethod } from './revoke-account-session.ts';
import { notificationPreferencesMethod } from './notification-preferences.ts';
import { accountNotificationsMethod } from './account-notifications.ts';
import { updateNotificationPreferencesMethod } from './update-notification-preferences.ts';
import { listProjectsForPrincipalMethod } from './list-projects-for-principal.ts';
import { personalThemesMethod } from './personal-themes.ts';
import { createPersonalThemeMethod } from './create-personal-theme.ts';
import { updatePersonalThemeMethod } from './update-personal-theme.ts';
import { deletePersonalThemeMethod } from './delete-personal-theme.ts';
import { accountDeletionBlockersMethod } from './account-deletion-blockers.ts';
import { deleteCurrentAccountMethod } from './delete-current-account.ts';
import { listTeamsForPrincipalMethod } from './list-teams-for-principal.ts';
import { listTeamProjectsMethod } from './list-team-projects.ts';
import { getProjectDetailsMethod } from './get-project-details.ts';
import { validatePrivateKnowledgeAccessMethod } from './validate-private-knowledge-access.ts';
import { recordPrivateKnowledgeOutcomeMethod } from './record-private-knowledge-outcome.ts';
import { getProjectDeploymentMethod } from './get-project-deployment.ts';
import { listProjectDeploymentsMethod } from './list-project-deployments.ts';
import { listProjectDeploymentEventsMethod } from './list-project-deployment-events.ts';
import { getProjectByTeamAndSlugMethod } from './get-project-by-team-and-slug.ts';
import { getProjectSummaryMethod } from './get-project-summary.ts';
import { getProjectAgentsSummaryMethod } from './get-project-agents-summary.ts';
import { getProjectReleasesSummaryMethod } from './get-project-releases-summary.ts';
import { getProjectCapacitySummaryMethod } from './get-project-capacity-summary.ts';
import { listApprovalRequestsForProjectMethod } from './list-approval-requests-for-project.ts';
import { listApprovalRequestsForTeamMethod } from './list-approval-requests-for-team.ts';
import { decideApprovalRequestMethod } from './decide-approval-request.ts';
import { getCommonsSummaryMethod } from './get-commons-summary.ts';
import { getCommonsParticipantMeMethod } from './get-commons-participant-me.ts';
import { listCommonsParticipantsMethod } from './list-commons-participants.ts';
import { backfillCommonsParticipantsMethod } from './backfill-commons-participants.ts';
import { listCommonsQuestionsMethod } from './list-commons-questions.ts';
import { answerCommonsQuestionMethod } from './answer-commons-question.ts';
import { createCommonsProposalMethod } from './create-commons-proposal.ts';
import { listCommonsProposalsMethod } from './list-commons-proposals.ts';
import { getCommonsProposalMethod } from './get-commons-proposal.ts';
import { reviewCommonsProposalMethod } from './review-commons-proposal.ts';
import { startCommonsProposalVotingMethod } from './start-commons-proposal-voting.ts';
import { stewardDecisionForCommonsProposalMethod } from './steward-decision-for-commons-proposal.ts';
import { listCommonsDecisionsMethod } from './list-commons-decisions.ts';
import { listCommonsEventsMethod } from './list-commons-events.ts';
import { deleteTeamInboxItemsByItemKeyMethod } from './delete-team-inbox-items-by-item-key.ts';
import { listPersistedTeamInboxItemsMethod } from './list-persisted-team-inbox-items.ts';
import { listAuditEventsForTargetMethod } from './list-audit-events-for-target.ts';
import { listTeamMembersMethod } from './list-team-members.ts';
import { getTeamAccessSummaryMethod } from './get-team-access-summary.ts';
import { getCommerceVendorMethod } from './get-commerce-vendor.ts';
import { requestCommerceVendorMethod } from './request-commerce-vendor.ts';
import { getCommerceVendorStripeStatusMethod } from './get-commerce-vendor-stripe-status.ts';
import { startCommerceVendorStripeOnboardingMethod } from './start-commerce-vendor-stripe-onboarding.ts';
import { markCommerceVendorStripeReturnMethod } from './mark-commerce-vendor-stripe-return.ts';
import { createCommerceVendorStripeLoginLinkMethod } from './create-commerce-vendor-stripe-login-link.ts';
import { listCommerceProductsMethod } from './list-commerce-products.ts';
import { getCommerceProductMethod } from './get-commerce-product.ts';
import { getCommerceOwnershipWorkflowMethod } from './get-commerce-ownership-workflow.ts';
import { updateCommerceOwnershipRecordMethod } from './update-commerce-ownership-record.ts';
import { updateCommerceStewardshipAssignmentMethod } from './update-commerce-stewardship-assignment.ts';
import { endCommerceStewardshipAssignmentMethod } from './end-commerce-stewardship-assignment.ts';
import { updateCommerceContributionMethod } from './update-commerce-contribution.ts';
import { updateCommerceGovernancePolicyMethod } from './update-commerce-governance-policy.ts';
import { submitCommerceOwnershipTransferMethod } from './submit-commerce-ownership-transfer.ts';
import { approveCommerceOwnershipTransferMethod } from './approve-commerce-ownership-transfer.ts';
import { rejectCommerceOwnershipTransferMethod } from './reject-commerce-ownership-transfer.ts';
import { cancelCommerceOwnershipTransferMethod } from './cancel-commerce-ownership-transfer.ts';
import { createCommerceSuccessionEventMethod } from './create-commerce-succession-event.ts';
import { listCommerceSuccessionEventsMethod } from './list-commerce-succession-events.ts';
import { getCommerceVendorSalesSummaryMethod } from './get-commerce-vendor-sales-summary.ts';
import { getCommerceVendorMonitoringMethod } from './get-commerce-vendor-monitoring.ts';
import { listCommerceMarketplaceProductsMethod } from './list-commerce-marketplace-products.ts';
import { getCommerceMarketplaceProductMethod } from './get-commerce-marketplace-product.ts';
import { listCommerceVendorSalesOrdersMethod } from './list-commerce-vendor-sales-orders.ts';
import { listCommerceVendorSalesSubscriptionsMethod } from './list-commerce-vendor-sales-subscriptions.ts';
import { listCommerceVendorSalesEntitlementsMethod } from './list-commerce-vendor-sales-entitlements.ts';
import { listCommerceVendorSalesRefundsMethod } from './list-commerce-vendor-sales-refunds.ts';
import { listCommerceVendorFulfillmentEventsMethod } from './list-commerce-vendor-fulfillment-events.ts';
import { createCommerceOrderRefundMethod } from './create-commerce-order-refund.ts';
import { fulfillCommerceOrderItemArtifactMethod } from './fulfill-commerce-order-item-artifact.ts';
import { revokeCommerceEntitlementMethod } from './revoke-commerce-entitlement.ts';
import { createCommerceServiceRequestMethod } from './create-commerce-service-request.ts';
import { listCommerceServiceRequestsMethod } from './list-commerce-service-requests.ts';
import { getCommerceServiceRequestMethod } from './get-commerce-service-request.ts';
import { startCommerceServiceScopingMethod } from './start-commerce-service-scoping.ts';
import { updateCommerceServiceRequestMethod } from './update-commerce-service-request.ts';
import { cancelCommerceServiceRequestMethod } from './cancel-commerce-service-request.ts';
import { createCommerceServiceQuoteMethod } from './create-commerce-service-quote.ts';
import { listCommerceServiceQuotesMethod } from './list-commerce-service-quotes.ts';
import { submitCommerceServiceQuoteMethod } from './submit-commerce-service-quote.ts';
import { buyerApproveCommerceServiceQuoteMethod } from './buyer-approve-commerce-service-quote.ts';
import { vendorApproveCommerceServiceQuoteMethod } from './vendor-approve-commerce-service-quote.ts';
import { rejectCommerceServiceQuoteMethod } from './reject-commerce-service-quote.ts';
import { getCommerceServiceContractMethod } from './get-commerce-service-contract.ts';
import { linkCommerceServiceContractWorkMethod } from './link-commerce-service-contract-work.ts';
import { fulfillCommerceServiceContractMethod } from './fulfill-commerce-service-contract.ts';
import { cancelCommerceServiceContractMethod } from './cancel-commerce-service-contract.ts';
import { listCommerceServiceEventsMethod } from './list-commerce-service-events.ts';
import { listCommerceCapacityListingsMethod } from './list-commerce-capacity-listings.ts';
import { getCommerceCapacityListingMethod } from './get-commerce-capacity-listing.ts';
import { getCommerceCapacityListingForProductMethod } from './get-commerce-capacity-listing-for-product.ts';
import { createCommerceCapacityListingMethod } from './create-commerce-capacity-listing.ts';
import { updateCommerceCapacityListingMethod } from './update-commerce-capacity-listing.ts';
import { submitCommerceCapacityListingMethod } from './submit-commerce-capacity-listing.ts';
import { approveCommerceCapacityListingMethod } from './approve-commerce-capacity-listing.ts';
import { rejectCommerceCapacityListingMethod } from './reject-commerce-capacity-listing.ts';
import { suspendCommerceCapacityListingMethod } from './suspend-commerce-capacity-listing.ts';
import { archiveCommerceCapacityListingMethod } from './archive-commerce-capacity-listing.ts';
import { createCommerceCapacityListingInquiryMethod } from './create-commerce-capacity-listing-inquiry.ts';
import { listCommerceCapacityListingInquiriesMethod } from './list-commerce-capacity-listing-inquiries.ts';
import { getCommerceCapacityListingInquiryMethod } from './get-commerce-capacity-listing-inquiry.ts';
import { reviewCommerceCapacityInquiryMethod } from './review-commerce-capacity-inquiry.ts';
import { approveCommerceCapacityInquiryForScopingMethod } from './approve-commerce-capacity-inquiry-for-scoping.ts';
import { declineCommerceCapacityInquiryMethod } from './decline-commerce-capacity-inquiry.ts';
import { cancelCommerceCapacityInquiryMethod } from './cancel-commerce-capacity-inquiry.ts';
import { evaluateTeamDeletionBlockersMethod } from './evaluate-team-deletion-blockers.ts';
import { evaluateProjectDeletionBlockersMethod } from './evaluate-project-deletion-blockers.ts';
import { listRepositoryHostsMethod } from './list-repository-hosts.ts';
import { getRepositoryHostMethod } from './get-repository-host.ts';
import { listTeamWebHostsMethod } from './list-team-web-hosts.ts';
import { getTeamTreeDxMethod } from './get-team-tree-dx.ts';
import { updateTeamTreeDxMethod } from './update-team-tree-dx.ts';
import { provisionTeamTreeDxMethod } from './provision-team-tree-dx.ts';
import { listTreeDxMirrorsMethod } from './list-tree-dx-mirrors.ts';
import { createTreeDxMirrorMethod } from './create-tree-dx-mirror.ts';
import { listTreeDxSharesMethod } from './list-tree-dx-shares.ts';
import { createTreeDxShareMethod } from './create-tree-dx-share.ts';
import { getProjectTreeDxLibraryMethod } from './get-project-tree-dx-library.ts';
import { upsertProjectTreeDxLibraryMethod } from './upsert-project-tree-dx-library.ts';
import { getProjectRepositoryTopologyMethod } from './get-project-repository-topology.ts';
import { updateProjectRepositoryTopologyMethod } from './update-project-repository-topology.ts';
import { getTeamWebHostMethod } from './get-team-web-host.ts';
import { listCapacityAllocationSetsMethod } from './list-capacity-allocation-sets.ts';
import { listProviderAvailabilitySessionsMethod } from './list-provider-availability-sessions.ts';
import { listProviderAssignmentsMethod } from './list-provider-assignments.ts';
import { listExecutionRunsMethod } from './list-execution-runs.ts';
import { listProjectAgentClassesMethod } from './list-project-agent-classes.ts';
import { listProjectAgentModeRunsMethod } from './list-project-agent-mode-runs.ts';
import { listProjectAgentFallbackOutputsMethod } from './list-project-agent-fallback-outputs.ts';
import { listProjectTreeDxProxyAuditMethod } from './list-project-tree-dx-proxy-audit.ts';
import { getProjectCapacityRuntimeDiagnosticsMethod } from './get-project-capacity-runtime-diagnostics.ts';
import { getProviderAssignmentExplanationMethod } from './get-provider-assignment-explanation.ts';
import { getDecisionPlanningStatusMethod } from './get-decision-planning-status.ts';
import { listDecisionExecutionInputsMethod } from './list-decision-execution-inputs.ts';
import { listDecisionCapacityPlansMethod } from './list-decision-capacity-plans.ts';
import { getCapacityPlanMethod } from './get-capacity-plan.ts';
import { getWorkdayCapacitySummaryMethod } from './get-workday-capacity-summary.ts';
import { listWorkdayRunsMethod } from './list-workday-runs.ts';
import { createWorkdayRunMethod } from './create-workday-run.ts';
import { getWorkdayRunMethod } from './get-workday-run.ts';
import { listCapacityLedgerEntriesMethod } from './list-capacity-ledger-entries.ts';
import { listCapacityRoutingDecisionsForProjectMethod } from './list-capacity-routing-decisions-for-project.ts';
import { listSeedRunsMethod } from './list-seed-runs.ts';
import { listCatalogItemsMethod } from './list-catalog-items.ts';
import { getCatalogItemBySlugMethod } from './get-catalog-item-by-slug.ts';
import { listCatalogArtifactVersionsMethod } from './list-catalog-artifact-versions.ts';
import { listKnowledgePacksMethod } from './list-knowledge-packs.ts';
import { acceptTeamInviteMethod } from './accept-team-invite.ts';
import { getTeamInviteMethod } from './get-team-invite.ts';
import { loadTeamProfileByNameMethod } from './load-team-profile-by-name.ts';
import { loadUserProfileByUsernameMethod } from './load-user-profile-by-username.ts';

export function installApiClientFacadeMethods(prototype: ApiClientFacade) {
	prototype.headers = headersMethod;
	prototype.url = urlMethod;
	prototype.request = requestMethod;
	prototype.accountIdentity = accountIdentityMethod;
	prototype.authProviders = authProvidersMethod;
	prototype.requestPasswordReset = requestPasswordResetMethod;
	prototype.completePasswordReset = completePasswordResetMethod;
	prototype.confirmEmail = confirmEmailMethod;
	prototype.approveDevice = approveDeviceMethod;
	prototype.claimUsername = claimUsernameMethod;
	prototype.updateAccountProfile = updateAccountProfileMethod;
	prototype.addAccountEmail = addAccountEmailMethod;
	prototype.resendAccountEmail = resendAccountEmailMethod;
	prototype.setPrimaryAccountEmail = setPrimaryAccountEmailMethod;
	prototype.deleteAccountEmail = deleteAccountEmailMethod;
	prototype.updateAccountPassword = updateAccountPasswordMethod;
	prototype.unlinkAccountProvider = unlinkAccountProviderMethod;
	prototype.accountSessions = accountSessionsMethod;
	prototype.revokeAccountSession = revokeAccountSessionMethod;
	prototype.notificationPreferences = notificationPreferencesMethod;
	prototype.accountNotifications = accountNotificationsMethod;
	prototype.updateNotificationPreferences = updateNotificationPreferencesMethod;
	prototype.listProjectsForPrincipal = listProjectsForPrincipalMethod;
	prototype.personalThemes = personalThemesMethod;
	prototype.createPersonalTheme = createPersonalThemeMethod;
	prototype.updatePersonalTheme = updatePersonalThemeMethod;
	prototype.deletePersonalTheme = deletePersonalThemeMethod;
	prototype.accountDeletionBlockers = accountDeletionBlockersMethod;
	prototype.deleteCurrentAccount = deleteCurrentAccountMethod;
	prototype.listTeamsForPrincipal = listTeamsForPrincipalMethod;
	prototype.listTeamProjects = listTeamProjectsMethod;
	prototype.getProjectDetails = getProjectDetailsMethod;
	prototype.validatePrivateKnowledgeAccess = validatePrivateKnowledgeAccessMethod;
	prototype.recordPrivateKnowledgeOutcome = recordPrivateKnowledgeOutcomeMethod;
	prototype.getProjectDeployment = getProjectDeploymentMethod;
	prototype.listProjectDeployments = listProjectDeploymentsMethod;
	prototype.listProjectDeploymentEvents = listProjectDeploymentEventsMethod;
	prototype.getProjectByTeamAndSlug = getProjectByTeamAndSlugMethod;
	prototype.getProjectSummary = getProjectSummaryMethod;
	prototype.getProjectAgentsSummary = getProjectAgentsSummaryMethod;
	prototype.getProjectReleasesSummary = getProjectReleasesSummaryMethod;
	prototype.getProjectCapacitySummary = getProjectCapacitySummaryMethod;
	prototype.listApprovalRequestsForProject = listApprovalRequestsForProjectMethod;
	prototype.listApprovalRequestsForTeam = listApprovalRequestsForTeamMethod;
	prototype.decideApprovalRequest = decideApprovalRequestMethod;
	prototype.getCommonsSummary = getCommonsSummaryMethod;
	prototype.getCommonsParticipantMe = getCommonsParticipantMeMethod;
	prototype.listCommonsParticipants = listCommonsParticipantsMethod;
	prototype.backfillCommonsParticipants = backfillCommonsParticipantsMethod;
	prototype.listCommonsQuestions = listCommonsQuestionsMethod;
	prototype.answerCommonsQuestion = answerCommonsQuestionMethod;
	prototype.createCommonsProposal = createCommonsProposalMethod;
	prototype.listCommonsProposals = listCommonsProposalsMethod;
	prototype.getCommonsProposal = getCommonsProposalMethod;
	prototype.reviewCommonsProposal = reviewCommonsProposalMethod;
	prototype.startCommonsProposalVoting = startCommonsProposalVotingMethod;
	prototype.stewardDecisionForCommonsProposal = stewardDecisionForCommonsProposalMethod;
	prototype.listCommonsDecisions = listCommonsDecisionsMethod;
	prototype.listCommonsEvents = listCommonsEventsMethod;
	prototype.deleteTeamInboxItemsByItemKey = deleteTeamInboxItemsByItemKeyMethod;
	prototype.listPersistedTeamInboxItems = listPersistedTeamInboxItemsMethod;
	prototype.listAuditEventsForTarget = listAuditEventsForTargetMethod;
	prototype.listTeamMembers = listTeamMembersMethod;
	prototype.getTeamAccessSummary = getTeamAccessSummaryMethod;
	prototype.getCommerceVendor = getCommerceVendorMethod;
	prototype.requestCommerceVendor = requestCommerceVendorMethod;
	prototype.getCommerceVendorStripeStatus = getCommerceVendorStripeStatusMethod;
	prototype.startCommerceVendorStripeOnboarding = startCommerceVendorStripeOnboardingMethod;
	prototype.markCommerceVendorStripeReturn = markCommerceVendorStripeReturnMethod;
	prototype.createCommerceVendorStripeLoginLink = createCommerceVendorStripeLoginLinkMethod;
	prototype.listCommerceProducts = listCommerceProductsMethod;
	prototype.getCommerceProduct = getCommerceProductMethod;
	prototype.getCommerceOwnershipWorkflow = getCommerceOwnershipWorkflowMethod;
	prototype.updateCommerceOwnershipRecord = updateCommerceOwnershipRecordMethod;
	prototype.updateCommerceStewardshipAssignment = updateCommerceStewardshipAssignmentMethod;
	prototype.endCommerceStewardshipAssignment = endCommerceStewardshipAssignmentMethod;
	prototype.updateCommerceContribution = updateCommerceContributionMethod;
	prototype.updateCommerceGovernancePolicy = updateCommerceGovernancePolicyMethod;
	prototype.submitCommerceOwnershipTransfer = submitCommerceOwnershipTransferMethod;
	prototype.approveCommerceOwnershipTransfer = approveCommerceOwnershipTransferMethod;
	prototype.rejectCommerceOwnershipTransfer = rejectCommerceOwnershipTransferMethod;
	prototype.cancelCommerceOwnershipTransfer = cancelCommerceOwnershipTransferMethod;
	prototype.createCommerceSuccessionEvent = createCommerceSuccessionEventMethod;
	prototype.listCommerceSuccessionEvents = listCommerceSuccessionEventsMethod;
	prototype.getCommerceVendorSalesSummary = getCommerceVendorSalesSummaryMethod;
	prototype.getCommerceVendorMonitoring = getCommerceVendorMonitoringMethod;
	prototype.listCommerceMarketplaceProducts = listCommerceMarketplaceProductsMethod;
	prototype.getCommerceMarketplaceProduct = getCommerceMarketplaceProductMethod;
	prototype.listCommerceVendorSalesOrders = listCommerceVendorSalesOrdersMethod;
	prototype.listCommerceVendorSalesSubscriptions = listCommerceVendorSalesSubscriptionsMethod;
	prototype.listCommerceVendorSalesEntitlements = listCommerceVendorSalesEntitlementsMethod;
	prototype.listCommerceVendorSalesRefunds = listCommerceVendorSalesRefundsMethod;
	prototype.listCommerceVendorFulfillmentEvents = listCommerceVendorFulfillmentEventsMethod;
	prototype.createCommerceOrderRefund = createCommerceOrderRefundMethod;
	prototype.fulfillCommerceOrderItemArtifact = fulfillCommerceOrderItemArtifactMethod;
	prototype.revokeCommerceEntitlement = revokeCommerceEntitlementMethod;
	prototype.createCommerceServiceRequest = createCommerceServiceRequestMethod;
	prototype.listCommerceServiceRequests = listCommerceServiceRequestsMethod;
	prototype.getCommerceServiceRequest = getCommerceServiceRequestMethod;
	prototype.startCommerceServiceScoping = startCommerceServiceScopingMethod;
	prototype.updateCommerceServiceRequest = updateCommerceServiceRequestMethod;
	prototype.cancelCommerceServiceRequest = cancelCommerceServiceRequestMethod;
	prototype.createCommerceServiceQuote = createCommerceServiceQuoteMethod;
	prototype.listCommerceServiceQuotes = listCommerceServiceQuotesMethod;
	prototype.submitCommerceServiceQuote = submitCommerceServiceQuoteMethod;
	prototype.buyerApproveCommerceServiceQuote = buyerApproveCommerceServiceQuoteMethod;
	prototype.vendorApproveCommerceServiceQuote = vendorApproveCommerceServiceQuoteMethod;
	prototype.rejectCommerceServiceQuote = rejectCommerceServiceQuoteMethod;
	prototype.getCommerceServiceContract = getCommerceServiceContractMethod;
	prototype.linkCommerceServiceContractWork = linkCommerceServiceContractWorkMethod;
	prototype.fulfillCommerceServiceContract = fulfillCommerceServiceContractMethod;
	prototype.cancelCommerceServiceContract = cancelCommerceServiceContractMethod;
	prototype.listCommerceServiceEvents = listCommerceServiceEventsMethod;
	prototype.listCommerceCapacityListings = listCommerceCapacityListingsMethod;
	prototype.getCommerceCapacityListing = getCommerceCapacityListingMethod;
	prototype.getCommerceCapacityListingForProduct = getCommerceCapacityListingForProductMethod;
	prototype.createCommerceCapacityListing = createCommerceCapacityListingMethod;
	prototype.updateCommerceCapacityListing = updateCommerceCapacityListingMethod;
	prototype.submitCommerceCapacityListing = submitCommerceCapacityListingMethod;
	prototype.approveCommerceCapacityListing = approveCommerceCapacityListingMethod;
	prototype.rejectCommerceCapacityListing = rejectCommerceCapacityListingMethod;
	prototype.suspendCommerceCapacityListing = suspendCommerceCapacityListingMethod;
	prototype.archiveCommerceCapacityListing = archiveCommerceCapacityListingMethod;
	prototype.createCommerceCapacityListingInquiry = createCommerceCapacityListingInquiryMethod;
	prototype.listCommerceCapacityListingInquiries = listCommerceCapacityListingInquiriesMethod;
	prototype.getCommerceCapacityListingInquiry = getCommerceCapacityListingInquiryMethod;
	prototype.reviewCommerceCapacityInquiry = reviewCommerceCapacityInquiryMethod;
	prototype.approveCommerceCapacityInquiryForScoping = approveCommerceCapacityInquiryForScopingMethod;
	prototype.declineCommerceCapacityInquiry = declineCommerceCapacityInquiryMethod;
	prototype.cancelCommerceCapacityInquiry = cancelCommerceCapacityInquiryMethod;
	prototype.evaluateTeamDeletionBlockers = evaluateTeamDeletionBlockersMethod;
	prototype.evaluateProjectDeletionBlockers = evaluateProjectDeletionBlockersMethod;
	prototype.listRepositoryHosts = listRepositoryHostsMethod;
	prototype.getRepositoryHost = getRepositoryHostMethod;
	prototype.listTeamWebHosts = listTeamWebHostsMethod;
	prototype.getTeamTreeDx = getTeamTreeDxMethod;
	prototype.updateTeamTreeDx = updateTeamTreeDxMethod;
	prototype.provisionTeamTreeDx = provisionTeamTreeDxMethod;
	prototype.listTreeDxMirrors = listTreeDxMirrorsMethod;
	prototype.createTreeDxMirror = createTreeDxMirrorMethod;
	prototype.listTreeDxShares = listTreeDxSharesMethod;
	prototype.createTreeDxShare = createTreeDxShareMethod;
	prototype.getProjectTreeDxLibrary = getProjectTreeDxLibraryMethod;
	prototype.upsertProjectTreeDxLibrary = upsertProjectTreeDxLibraryMethod;
	prototype.getProjectRepositoryTopology = getProjectRepositoryTopologyMethod;
	prototype.updateProjectRepositoryTopology = updateProjectRepositoryTopologyMethod;
	prototype.getTeamWebHost = getTeamWebHostMethod;
	prototype.listCapacityAllocationSets = listCapacityAllocationSetsMethod;
	prototype.listProviderAvailabilitySessions = listProviderAvailabilitySessionsMethod;
	prototype.listProviderAssignments = listProviderAssignmentsMethod;
	prototype.listExecutionRuns = listExecutionRunsMethod;
	prototype.listProjectAgentClasses = listProjectAgentClassesMethod;
	prototype.listProjectAgentModeRuns = listProjectAgentModeRunsMethod;
	prototype.listProjectAgentFallbackOutputs = listProjectAgentFallbackOutputsMethod;
	prototype.listProjectTreeDxProxyAudit = listProjectTreeDxProxyAuditMethod;
	prototype.getProjectCapacityRuntimeDiagnostics = getProjectCapacityRuntimeDiagnosticsMethod;
	prototype.getProviderAssignmentExplanation = getProviderAssignmentExplanationMethod;
	prototype.getDecisionPlanningStatus = getDecisionPlanningStatusMethod;
	prototype.listDecisionExecutionInputs = listDecisionExecutionInputsMethod;
	prototype.listDecisionCapacityPlans = listDecisionCapacityPlansMethod;
	prototype.getCapacityPlan = getCapacityPlanMethod;
	prototype.getWorkdayCapacitySummary = getWorkdayCapacitySummaryMethod;
	prototype.listWorkdayRuns = listWorkdayRunsMethod;
	prototype.createWorkdayRun = createWorkdayRunMethod;
	prototype.getWorkdayRun = getWorkdayRunMethod;
	prototype.listCapacityLedgerEntries = listCapacityLedgerEntriesMethod;
	prototype.listCapacityRoutingDecisionsForProject = listCapacityRoutingDecisionsForProjectMethod;
	prototype.listSeedRuns = listSeedRunsMethod;
	prototype.listCatalogItems = listCatalogItemsMethod;
	prototype.getCatalogItemBySlug = getCatalogItemBySlugMethod;
	prototype.listCatalogArtifactVersions = listCatalogArtifactVersionsMethod;
	prototype.listKnowledgePacks = listKnowledgePacksMethod;
	prototype.acceptTeamInvite = acceptTeamInviteMethod;
	prototype.getTeamInvite = getTeamInviteMethod;
	prototype.loadTeamProfileByName = loadTeamProfileByNameMethod;
	prototype.loadUserProfileByUsername = loadUserProfileByUsernameMethod;
}
