import type { TreeseedSiteRouteContribution } from '@treeseed/sdk/platform/plugin';

export const ADMIN_ROUTES: TreeseedSiteRouteContribution[] = [
	{ pattern: '/app', resourcePath: 'pages/app/index.astro' },
	{ pattern: '/app/account', resourcePath: 'pages/app/account.astro' },
	{ pattern: '/app/teams', resourcePath: 'pages/app/teams/index.astro' },
	{ pattern: '/app/teams/new', resourcePath: 'pages/app/teams/new.astro' },
	{ pattern: '/app/teams/[teamId]/edit', resourcePath: 'pages/app/teams/[teamId]/edit.astro' },
	{ pattern: '/app/teams/[teamId]/delete', resourcePath: 'pages/app/teams/[teamId]/delete.astro' },
	{ pattern: '/app/teams/[teamId]/members', resourcePath: 'pages/app/teams/[teamId]/members.astro' },
	{ pattern: '/auth/register', resourcePath: 'pages/auth/register.astro' },
	{ pattern: '/auth/check-email', resourcePath: 'pages/auth/check-email.astro' },
	{ pattern: '/auth/confirm-email', resourcePath: 'pages/auth/confirm-email.astro' },
	{ pattern: '/auth/sign-in', resourcePath: 'pages/auth/sign-in.astro' },
	{ pattern: '/auth/logout', resourcePath: 'pages/auth/logout.astro' },
	{ pattern: '/auth/forgot-password', resourcePath: 'pages/auth/forgot-password.astro' },
	{ pattern: '/auth/reset-password', resourcePath: 'pages/auth/reset-password.astro' },
	{ pattern: '/auth/username', resourcePath: 'pages/auth/username.astro' },
	{ pattern: '/auth/device/approve', resourcePath: 'pages/auth/device/approve.astro' },
	{ pattern: '/auth/callback/[provider]', resourcePath: 'pages/auth/callback/[provider].ts' },
	{ pattern: '/u/[username]', resourcePath: 'pages/u/[username].astro' },
	{ pattern: '/t/[name]', resourcePath: 'pages/t/[name].astro' },
	{ pattern: '/team-invites/[token]/accept', resourcePath: 'pages/team-invites/[token]/accept.astro' },
	{ pattern: '/v1/[...all]', resourcePath: 'pages/v1/[...all].ts' },
];
